### PR TITLE
Profile page

### LINKED ISSUE #13: User Profile Page
This is the page where users can post their plant pictures and details, share their planting tips and other stuff that will be helpful to other users

Figma wireframe - https://www.figma.com/file/gUdZcQKYryEyy70LMHuJTI/Growers-Brains-MVP?node-id=0%3A88

--MVP requirements--
- Name
- Date joined
- Profile picture
- All Images ever uploaded Including -image uploaded for disease scanning and others
- A short Bio them

### PR DESCRIPTION
**Pull request by harshlele**
# Description

Fixes #13 

## Changes made:
- MVP of a profile page 

 # Type of change:
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:
  - [x] I have read the contributing documentation.
  - [x] My code follows the code style of this project.
  - [ ] My code has been linted.
  - [x] I have performed a self-review of my code.
  - [ ] I have commented my code, particularly the hard to understand areas.
  - [ ] I have added tests to cover my changes (if applicable).
  - [x] My changes generate no new warnings.
  - [x] There are no merge conflicts.

### CODE REVIEW

**Comment by nuggetnchill** [comment]
@harshlele can you resolve the conflict realquick?

**Comment by harshlele** [comment]
@nuggetnchill done

**Review by GoGi2712 — APPROVED** [review]

**Comment by harshlele** [comment]
hey hold on to this don't merge it yet. @AbSamad99 is working on a few more changes(the "What's in my garden" section). We can merge after he pushes his changes @robpedersendev

**Review by harman099 — APPROVED** [review]

**Comment by harshlele** [comment]
@harman099 @GoGi2712 can you review it again now? i think this can be merged again

**Comment by harshlele** [comment]
image
@robpedersendev

**Review by GoGi2712 — APPROVED** [review]
Yes!!Great.

**Pull request merged**
